#!/usr/bin/python


import argparse
import requests
from requests.auth import HTTPBasicAuth
import re
from lxml import html


class Agent(object):

    def __init__(self, hostname, username, password):
        self.session = requests.Session()
        self.hostname = hostname
        self.username = username
        self.password = password

    @property
    def auth(self):
        return HTTPBasicAuth(self.username, self.password)

    def check(self):
        url = 'http://{}/information.asp'.format(self.hostname)
        r = self.session.get(url, auth=self.auth)
        r.raise_for_status()

        doc = html.fromstring(r.content)
        uptime_text = None
        for row in doc.xpath('//tr'):
            tds = row.xpath('.//td')
            if tds[0].text_content().strip() == 'Up time':
                uptime_text = tds[1].text_content().strip()

        if not uptime_text:
            raise Exception('Could not find uptime')

        uptime_seconds = self.parse_uptime(uptime_text)
        print('<<<uptime>>>')
        print(uptime_seconds)

    def parse_uptime(self, text):
        m = re.match('^(\d+)day:(\d+)h:(\d+)m:(\d+)s$', text)
        if m:
            return (
                int(m.group(1)) * 24 * 3600 +
                int(m.group(2)) * 3600 +
                int(m.group(3)) * 60 +
                int(m.group(4))
            )


def main():
    args = parse_args()
    agent = Agent(args.hostname, args.username, args.password)
    agent.check()


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--username', default='admin')
    parser.add_argument('--password', default='1234')
    parser.add_argument('hostname')
    return parser.parse_args()


if __name__ == '__main__':
    main()
